language: cpp
compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq devscripts build-essential equivs python-all

install:
  - sudo apt-get install -qq cmake libboost-dev libboost-test-dev

before_script:
  - mkdir build && cd build

script:
  - cmake .. && make 
  - ctest --verbose
